#!/usr/bin/env python3
"""
This module calculates the sum of integers from 2 to 5 using a loop.
"""

def sigma():
    """
    Returns the sum of integers from 2 to 5.
    """
    total = 0
    for i in range(2, 6):
        total += i
    return total

if __name__ == "__main__":
    print(sigma())
